Entity/EventTriggerInterface.php
<?php

namespace Oro\Bundle\WorkflowBundle\Entity;

interface EventTriggerInterface
{
    const EVENT_CREATE = 'create';
    const EVENT_UPDATE = 'update';
    const EVENT_DELETE = 'delete';

    /**
     * @return int
     */
    public function getId();

    /**
     * @return string
     */
    public function getEntityClass();

    /**
     * @return string
     */
    public function getEvent();

    /**
     * @return string
     */
    public function getField();
}

Entity/ProcessDefinition.php
<?php

namespace Oro\Bundle\WorkflowBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Oro\Bundle\EntityConfigBundle\Metadata\Annotation\Config;
use Oro\Bundle\EntityConfigBundle\Metadata\Annotation\ConfigField;

use Symfony\Component\Security\Acl\Model\DomainObjectInterface;

/**
 * @ORM\Table("oro_process_definition")
 * @ORM\Entity(repositoryClass="Oro\Bundle\WorkflowBundle\Entity\Repository\ProcessDefinitionRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Config(
 *      routeName="oro_process_definition_index",
 *      routeView="oro_process_definition_view",
 *      defaultValues={
 *          "entity"={
 *              "icon"="icon-inbox"
 *          },
 *          "security"={
 *              "type"="ACL",
 *              "group_name"="",
 *              "category"="account_management"
 *          },
 *          "note"={
 *              "immutable"=true
 *          },
 *          "activity"={
 *              "immutable"=true
 *          },
 *          "attachment"={
 *              "immutable"=true
 *          }
 *      }
 * )
 */
class ProcessDefinition implements DomainObjectInterface
{
    /**
     * @var string
     *
     * @ORM\Id
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="label", type="string", length=255)
     */
    protected $label;

    /**
     * @var boolean
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    protected $enabled = true;

    /**
     * @var string
     *
     * @ORM\Column(name="related_entity", type="string", length=255)
     */
    protected $relatedEntity;

    /**
     * @var integer
     *
     * @ORM\Column(name="execution_order", type="smallint")
     */
    protected $executionOrder = 0;

    /**
     * @var array
     *
     * @ORM\Column(name="exclude_definitions", type="simple_array", nullable=true)
     */
    protected $excludeDefinitions = [];

    /**
     * @var array
     *
     * @ORM\Column(name="pre_conditions_configuration", type="array", nullable=true)
     */
    protected $preConditionsConfiguration;

    /**
     * @var array
     *
     * @ORM\Column(name="actions_configuration", type="array")
     */
    protected $actionsConfiguration;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @ConfigField(
     *      defaultValues={
     *          "entity"={
     *              "label"="oro.ui.created_at"
     *          }
     *      }
     * )
     */
    protected $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     * @ConfigField(
     *      defaultValues={
     *          "entity"={
     *              "label"="oro.ui.updated_at"
     *          }
     *      }
     * )
     */
    protected $updatedAt;

    /**
     * @param string $name
     * @return ProcessDefinition
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $label
     * @return ProcessDefinition
     */
    public function setLabel($label)
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * @param boolean $enabled
     * @return ProcessDefinition
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isEnabled()
    {
        return $this->enabled;
    }

    /**
     * @param string $relatedEntity
     * @return ProcessDefinition
     */
    public function setRelatedEntity($relatedEntity)
    {
        $this->relatedEntity = $relatedEntity;

        return $this;
    }

    /**
     * @return string
     */
    public function getRelatedEntity()
    {
        return $this->relatedEntity;
    }

    /**
     * @param integer $executionOrder
     * @return ProcessDefinition
     */
    public function setExecutionOrder($executionOrder)
    {
        $this->executionOrder = $executionOrder;

        return $this;
    }

    /**
     * @return integer
     */
    public function getExecutionOrder()
    {
        return $this->executionOrder;
    }

    /**
     * @param array $excludeDefinitions
     * @return ProcessDefinition
     */
    public function setExcludeDefinitions(array $excludeDefinitions)
    {
        $this->excludeDefinitions = $excludeDefinitions;

        return $this;
    }

    /**
     * @return array
     */
    public function getExcludeDefinitions()
    {
        return (array)$this->excludeDefinitions;
    }

    /**
     * @return array
     */
    public function getPreConditionsConfiguration()
    {
        return $this->preConditionsConfiguration;
    }

    /**
     * @param array $configuration
     * @return ProcessDefinition
     */
    public function setPreConditionsConfiguration($configuration)
    {
        $this->preConditionsConfiguration = $configuration;

        return $this;
    }

    /**
     * @param array $configuration
     * @return ProcessDefinition
     */
    public function setActionsConfiguration($configuration)
    {
        $this->actionsConfiguration = $configuration;

        return $this;
    }

    /**
     * @return array
     */
    public function getActionsConfiguration()
    {
        return $this->actionsConfiguration;
    }

    /**
     * @param \DateTime $createdAt
     * @return ProcessDefinition
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $updatedAt
     * @return ProcessDefinition
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->createdAt = new \DateTime('now', new \DateTimeZone('UTC'));
        $this->preUpdate();
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        $this->updatedAt = new \DateTime('now', new \DateTimeZone('UTC'));
    }

    /**
     * @param ProcessDefinition $definition
     * @return ProcessDefinition
     */
    public function import(ProcessDefinition $definition)
    {
        // enabled flag should not be imported
        $this->setName($definition->getName())
            ->setLabel($definition->getLabel())
            ->setRelatedEntity($definition->getRelatedEntity())
            ->setExecutionOrder($definition->getExecutionOrder())
            ->setActionsConfiguration($definition->getActionsConfiguration())
            ->setExcludeDefinitions($definition->getExcludeDefinitions())
            ->setPreConditionsConfiguration($definition->getPreConditionsConfiguration());

        return $this;
    }

    /**
     * Returns a unique identifier for this domain object.
     *
     * @return string
     */
    public function getObjectIdentifier()
    {
        return $this->getName();
    }
}

Controller/ProcessDefinitionController.php
<?php

namespace Oro\Bundle\WorkflowBundle\Controller;

use Oro\Bundle\SecurityBundle\Annotation\Acl;
use Oro\Bundle\SecurityBundle\Annotation\AclAncestor;
use Oro\Bundle\WorkflowBundle\Entity\ProcessDefinition;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/processdefinition")
 */
class ProcessDefinitionController extends Controller
{
    /**
     * @Route(name="oro_process_definition_index")
     * @Template
     * @Acl(
     *      id="oro_process_definition_view",
     *      type="entity",
     *      class="OroWorkflowBundle:ProcessDefinition",
     *      permission="VIEW"
     * )
     *
     * @return array
     */
    public function indexAction()
    {
        return array();
    }

    /**
     * @Route(
     *      "/view/{name}",
     *      name="oro_process_definition_view"
     * )
     * @AclAncestor("oro_process_definition_view")
     * @Template("OroWorkflowBundle:ProcessDefinition:view.html.twig")
     *
     * @param ProcessDefinition $processDefinition
     * @return array
     */
    public function viewAction(ProcessDefinition $processDefinition)
    {
        $triggers = $this->getRepository('OroWorkflowBundle:ProcessTrigger')
            ->findBy(array('definition' => $processDefinition));
        return array(
            'entity'   => $processDefinition,
            'triggers' => $triggers
        );
    }

    /**
     * @param string $entityName
     * @return \Doctrine\Common\Persistence\ObjectRepository
     */
    protected function getRepository($entityName)
    {
        return $this->getDoctrine()->getRepository($entityName);
    }
}

Resources/views/ProcessDefinition/index.html.twig
{% extends 'OroUIBundle:actions:index.html.twig' %}
{% set gridName = 'process-definitions-grid' %}
{% set pageTitle = 'oro.workflow.processdefinition.entity_plural_label'|trans %}

Resources/views/ProcessDefinition/view.html.twig
{% extends 'OroUIBundle:actions:view.html.twig' %}

{% oro_title_set({params : {"%process_definition.label%": entity.label} }) %}

{% block navButtons %}
    {% if resource_granted('oro_process_definition_update') %}
        {% set idButton = entity.name ~ '-process-deactivate-btn' %}
        {% if entity.enabled %}
            {{ UI.button({
                'aCss':  'no-hash btn-danger',
                'iCss':  'icon-remove',
                'id':    idButton,
                'label': 'oro.workflow.action.process.deactivate'|trans,
                'path':  path('oro_api_process_deactivate', {'processDefinition': entity.name}),
                'title': 'oro.workflow.action.process.deactivate'|trans,
            }) }}
        {% else %}
            {{ UI.button({
                'iCss':  'icon-ok',
                'aCss':  'no-hash btn-success',
                'id':    idButton,
                'label': 'oro.workflow.action.process.activate'|trans,
                'path':  path('oro_api_process_activate', {'processDefinition': entity.name}),
                'title': 'oro.workflow.action.process.activate'|trans,
            }) }}
        {% endif %}
        <script type="text/javascript">
            require(['jquery', 'oroui/js/mediator', 'oroui/js/error'],
            function($, mediator, Error) {
                $('#{{ idButton }}').on('click', function(e) {
                    e.preventDefault();
                    var el = $(this);
                    $.ajax({
                        url: el.prop('href'),
                        type: 'GET',
                        success: function(response) {
                            if (response.message) {
                                mediator.once('page:afterChange', function() {
                                    mediator.execute('showFlashMessage', 'success', response.message);
                                });
                            }
                            mediator.execute('refreshPage');
                        },
                        error: function(xhr) {
                            Error.handle({}, xhr, {enforce: true});
                        }
                    })
                });
            });
        </script>
    {% endif %}
{% endblock navButtons %}

{% block breadcrumbs %}
    {{ parent() }}

    <div class="pull-left">
        {% if entity.enabled %}
            <div class="badge badge-enabled status-enabled"><i class="icon-status-enabled icon-circle"></i>{{ 'Active'|trans }}</div>
        {% else %}
            <div class="badge badge-disabled status-disabled"><i class="icon-status-disabled icon-circle"></i>{{ 'Inactive'|trans }}</div>
        {% endif %}
    </div>
{% endblock breadcrumbs %}

{% block stats %}
    <li>{{ 'oro.ui.created_at'|trans }}: {{ entity.createdAt ? entity.createdAt|oro_format_datetime : 'N/A' }}</li>
    <li>{{ 'oro.ui.updated_at'|trans }}: {{ entity.updatedAt ? entity.updatedAt|oro_format_datetime : 'N/A' }}</li>
{% endblock stats %}

{% block pageHeader %}
    {% set breadcrumbs = {
        'entity': entity,
        'indexPath': path('oro_process_definition_index'),
        'indexLabel': 'oro.workflow.processdefinition.entity_plural_label'|trans,
        'entityTitle': entity.label
    } %}
    {{ parent() }}
{% endblock pageHeader %}

{% block content_data %}
    {%- set processDefinitionInfo -%}
        {% set entityConfig = oro_entity_config(entity.relatedEntity) %}
        {% set relatedEntityLabel = entityConfig.label|default('')|trans %}

        {%- set triggerData -%}
            {%- for trigger in triggers -%}
                {% if trigger.event %}
                    {% set event = 'oro.workflow.block.view.process.trigger.event.' ~ trigger.event  %}
                    {% set when = trigger.queued ?
                        trigger.timeShift|oro_format_duration :
                        'oro.workflow.block.view.process.trigger.when.immediately'|trans
                    %}

                    {% if trigger.field %}
                        {% set field = entityConfig.trigger.field.lable|default(trigger.field) %}
                        {% set after = '<b>' ~ field ~ '</b> ' ~ 'oro.workflow.block.view.process.trigger.after.property'|trans %}
                    {% else %}
                        {% set after = '<b>' ~ relatedEntityLabel ~ '</b> ' ~ 'oro.workflow.block.view.process.trigger.after.entity'|trans %}
                    {% endif %}

                    {{ 'oro.workflow.block.view.process.trigger.description'|trans({
                            '%after%': after,
                            '%event%': '<b>' ~ event|trans ~ '</b>',
                            '%when%':  '<b>' ~ when ~ '</b>'
                        })|raw
                    }}
                    <br />
                {% elseif trigger.cron %}
                    {{ 'oro.workflow.block.view.process.trigger.cron.description'|trans({
                        '{{ cron }}': '<b>' ~ trigger.cron ~ '</b>'
                    })|raw }}
                    <br />
                {% endif %}
            {%- endfor -%}
        {%- endset -%}

        <div class="row-fluid form-horizontal">
            <div class="responsive-block">
                {{ UI.renderProperty('oro.workflow.processdefinition.label.label'|trans, entity.label) }}
                {{ UI.renderProperty('oro.workflow.processdefinition.related_entity.label'|trans, relatedEntityLabel) }}
                {{ UI.renderProperty('oro.workflow.processdefinition.execution_order.label'|trans, entity.executionOrder) }}
                {{ UI.renderHtmlProperty('oro.workflow.processtrigger.entity_plural_label'|trans, triggerData) }}
            </div>
        </div>
    {%- endset -%}

    {% set dataBlocks = [
        {
            'title': 'oro.workflow.block.title.process_info'|trans,
            'class': 'active',
            'subblocks': [
                {'data' : [processDefinitionInfo] },
            ]
        }
    ] %}

    {% set id = 'processDefinitionView' %}
    {% set data = {'dataBlocks': dataBlocks} %}
    {{ parent() }}
{% endblock content_data %}